name = "django-yilin"
compatibility_date = "2024-01-01"

[build]
command = "pip install -r requirements.txt && python manage.py collectstatic --noinput"
publish = "staticfiles"

[env.production]
PYTHON_VERSION = "3.10.6"
DJANGO_SETTINGS_MODULE = "welfare_config.settings"
DEBUG = "False"
ALLOWED_HOSTS = "*.pages.dev, localhost, 127.0.0.1"
