[build]
command = "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
publish = "staticfiles"

[build.environment]
PYTHON_VERSION = "3.10.6"
DJANGO_SETTINGS_MODULE = "welfare_config.settings"
DEBUG = "False"
ALLOWED_HOSTS = "*.pages.dev,localhost,127.0.0.1"
