# Generated by Django 4.2 on 2024-12-28 03:13

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(default='暂无简介', verbose_name='简介')),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/', verbose_name='封面图')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='活动内容')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('location', models.CharField(max_length=200, verbose_name='活动地点')),
                ('volunteers_needed', models.IntegerField(default=1, verbose_name='所需志愿者')),
                ('volunteers_registered', models.IntegerField(default=0, verbose_name='已报名志愿者')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否进行中')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '活动信息',
                'verbose_name_plural': '活动信息',
                'ordering': ['-is_featured', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('image', models.ImageField(upload_to='carousel/', verbose_name='图片')),
                ('link', models.URLField(blank=True, verbose_name='链接')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'ordering': ['order', '-created_time'],
            },
        ),
        migrations.CreateModel(
            name='ServiceHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('description', models.TextField(default='', verbose_name='描述')),
                ('icon', models.CharField(default='', help_text='Font Awesome图标类名', max_length=50, verbose_name='图标类名')),
                ('index', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '服务亮点',
                'verbose_name_plural': '服务亮点',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('value', models.CharField(max_length=50, verbose_name='数值')),
                ('icon', models.CharField(default='', help_text='Font Awesome图标类名', max_length=50, verbose_name='图标类名')),
                ('index', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '统计数据',
                'verbose_name_plural': '统计数据',
                'ordering': ['index'],
            },
        ),
    ]
