# Generated by Django 4.2 on 2024-12-28 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('volunteerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteeractivity',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='申请时间'),
        ),
    ]
