# Generated by Django 5.0 on 2024-12-27 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='活动标题')),
                ('description', models.TextField(verbose_name='活动描述')),
                ('date', models.DateField(verbose_name='活动日期')),
                ('location', models.CharField(max_length=100, verbose_name='活动地点')),
                ('volunteers_needed', models.IntegerField(verbose_name='所需志愿者数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '志愿活动',
                'verbose_name_plural': '志愿活动',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('apply_reason', models.TextField(verbose_name='申请理由')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.activity', verbose_name='活动')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '志愿申请',
                'verbose_name_plural': '志愿申请',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'activity')},
            },
        ),
    ]
