# Generated by Django 4.2 on 2024-12-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_number',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_photo_back',
            field=models.ImageField(blank=True, null=True, upload_to='id_photos/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_photo_front',
            field=models.ImageField(blank=True, null=True, upload_to='id_photos/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='identity_status',
            field=models.CharField(choices=[('unverified', '未验证'), ('pending', '审核中'), ('verified', '已验证'), ('rejected', '已拒绝')], default='unverified', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='real_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to='avatars/%Y/%m/', verbose_name='头像'),
        ),
    ]
