# Generated by Django 4.2 on 2024-12-28 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userApp', '0006_emergencycontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='身高(cm)')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='体重(kg)')),
                ('blood_type', models.CharField(choices=[('A', 'A型'), ('B', 'B型'), ('O', 'O型'), ('AB', 'AB型'), ('unknown', '未知')], default='unknown', max_length=10, verbose_name='血型')),
                ('allergies', models.TextField(blank=True, verbose_name='过敏史')),
                ('medical_history', models.TextField(blank=True, verbose_name='既往病史')),
                ('medications', models.TextField(blank=True, verbose_name='当前用药')),
                ('emergency_medical_info', models.TextField(blank=True, verbose_name='紧急医疗信息')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '健康信息',
                'verbose_name_plural': '健康信息',
            },
        ),
    ]
