# Generated by Django 4.2 on 2024-12-28 03:13

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='服务名称')),
                ('image', models.ImageField(upload_to='services/', verbose_name='服务图片')),
                ('short_description', models.TextField(verbose_name='简短描述')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='服务详情')),
                ('price', models.DecimalField(decimal_places=2, help_text='元/次', max_digits=10, verbose_name='价格')),
                ('duration', models.CharField(help_text='如：2小时', max_length=50, verbose_name='服务时长')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否特色服务')),
                ('status', models.CharField(choices=[('active', '正常'), ('suspended', '暂停'), ('discontinued', '停止')], default='active', max_length=20, verbose_name='服务状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '服务项目',
                'verbose_name_plural': '服务项目',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='类别名称')),
                ('description', models.TextField(verbose_name='类别描述')),
                ('icon', models.CharField(help_text='Font Awesome图标类名', max_length=50, verbose_name='图标类名')),
                ('index', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '服务类别',
                'verbose_name_plural': '服务类别',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='ServiceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='评分')),
                ('comment', models.TextField(verbose_name='评价内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceApp.service', verbose_name='服务项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评价用户')),
            ],
            options={
                'verbose_name': '服务评价',
                'verbose_name_plural': '服务评价',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='预约时间')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='预约状态')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceApp.service', verbose_name='服务项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='预约用户')),
            ],
            options={
                'verbose_name': '服务预约',
                'verbose_name_plural': '服务预约',
                'ordering': ['-appointment_time'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceApp.servicecategory', verbose_name='服务类别'),
        ),
    ]
