# Generated by Django 4.2 on 2024-12-28 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceApp', '0002_alter_service_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicereview',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='serviceApp.service', verbose_name='服务项目'),
        ),
    ]
