# Generated by Django 4.2 on 2024-12-29 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceApp', '0004_rename_comment_to_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicereview',
            options={'ordering': ['-created_at'], 'verbose_name': '服务评价', 'verbose_name_plural': '服务评价'},
        ),
    ]
