# Generated by Django 4.2 on 2024-12-28 14:27

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='分类描述')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='分类图标')),
            ],
            options={
                'verbose_name': '培训课程分类',
                'verbose_name_plural': '培训课程分类',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='课程标题')),
                ('description', ckeditor.fields.RichTextField(verbose_name='课程描述')),
                ('difficulty', models.CharField(choices=[('basic', '入门级'), ('intermediate', '中级'), ('advanced', '高级')], default='basic', max_length=20, verbose_name='难度等级')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('closed', '已结束')], default='draft', max_length=20, verbose_name='课程状态')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('duration', models.IntegerField(verbose_name='课程时长（分钟）')),
                ('max_participants', models.IntegerField(verbose_name='最大参与人数')),
                ('current_participants', models.IntegerField(default=0, verbose_name='当前参与人数')),
                ('instructor', models.CharField(max_length=100, verbose_name='授课讲师')),
                ('location', models.CharField(max_length=200, verbose_name='培训地点')),
                ('image', models.ImageField(blank=True, null=True, upload_to='training_images/', verbose_name='课程封面')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings', to='trainingApp.trainingcategory', verbose_name='课程分类')),
            ],
            options={
                'verbose_name': '培训课程',
                'verbose_name_plural': '培训课程',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='TrainingApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='报名状态')),
                ('message', models.TextField(blank=True, null=True, verbose_name='申请备注')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='trainingApp.training', verbose_name='培训课程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_applications', to=settings.AUTH_USER_MODEL, verbose_name='报名用户')),
            ],
            options={
                'verbose_name': '培训课程报名',
                'verbose_name_plural': '培训课程报名',
                'unique_together': {('user', 'training')},
            },
        ),
    ]
